-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 21:23:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cvdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cvdb` ;

-- -----------------------------------------------------
-- Schema cvdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cvdb` DEFAULT CHARACTER SET utf8 ;
USE `cvdb` ;

-- -----------------------------------------------------
-- Table `cvdb`.`akun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`akun` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`akun` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(25) NOT NULL,
  `EMAIL` VARCHAR(30) NULL DEFAULT NULL,
  `PW` VARCHAR(30) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `UNI_USERNAME` USING BTREE ON `cvdb`.`akun` (`USERNAME` ASC);


-- -----------------------------------------------------
-- Table `cvdb`.`datadiri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`datadiri` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`datadiri` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAMA_LENGKAP` VARCHAR(50) NULL DEFAULT NULL,
  `UMUR` VARCHAR(45) NULL DEFAULT NULL,
  `TEMPAT_LAHIR` VARCHAR(25) NULL DEFAULT NULL,
  `TANGGAL_LAHIR` DATE NULL DEFAULT NULL,
  `GENDER` CHAR(1) NULL DEFAULT NULL,
  `AGAMA` VARCHAR(10) NULL DEFAULT NULL,
  `KEWARGANEGARAAN` VARCHAR(15) NULL DEFAULT NULL,
  `STATUS_PERKAWINAN` VARCHAR(8) NULL DEFAULT NULL,
  `TINGGI` VARCHAR(3) NULL DEFAULT NULL,
  `BERAT` VARCHAR(3) NULL DEFAULT NULL,
  `ALAMAT` VARCHAR(50) NULL DEFAULT NULL,
  `FOTO` VARCHAR(50) NULL DEFAULT NULL,
  `PROFIL_SINGKAT` VARCHAR(150) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`ID`),
  CONSTRAINT `FK_akun`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`akun` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cvdb`.`organisasi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`organisasi` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`organisasi` (
  `ORGANISASI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID` INT(11) NULL DEFAULT NULL,
  `NAMA_ORGANISASI` VARCHAR(45) NULL DEFAULT NULL,
  `JABATAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(100) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ORGANISASI_ID`),
  CONSTRAINT `FK_org`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`datadiri` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_org_idx` ON `cvdb`.`organisasi` (`ID` ASC);


-- -----------------------------------------------------
-- Table `cvdb`.`pekerjaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`pekerjaan` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`pekerjaan` (
  `PEKERJAAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID` INT(11) NULL DEFAULT NULL,
  `NAMA_PERUSAHAAN` VARCHAR(45) NULL DEFAULT NULL,
  `JABATAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(100) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PEKERJAAN_ID`),
  CONSTRAINT `FK_pekerjaan_datadiri`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`datadiri` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_pekerjaan_datadiri_idx` ON `cvdb`.`pekerjaan` (`ID` ASC);


-- -----------------------------------------------------
-- Table `cvdb`.`pendidikan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`pendidikan` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`pendidikan` (
  `PENDIDIKAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID` INT(11) NULL DEFAULT NULL,
  `NAMA_SEKOLAH` VARCHAR(50) NULL DEFAULT NULL,
  `JURUSAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `IPK` VARCHAR(4) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PENDIDIKAN_ID`),
  CONSTRAINT `FK_pendidikan_datadiri`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`datadiri` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_pendidikan_datadiri_idx` ON `cvdb`.`pendidikan` (`ID` ASC);


-- -----------------------------------------------------
-- Table `cvdb`.`penghargaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`penghargaan` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`penghargaan` (
  `PENGHARGAAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID` INT(11) NULL DEFAULT NULL,
  `PENGHARGAAN` VARCHAR(30) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(50) NULL DEFAULT NULL,
  `GAMBAR` VARCHAR(50) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PENGHARGAAN_ID`),
  CONSTRAINT `FK_penghargaan_datadiri`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`datadiri` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_penghargaan_datadiri_idx` ON `cvdb`.`penghargaan` (`ID` ASC);


-- -----------------------------------------------------
-- Table `cvdb`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`skill` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`skill` (
  `SKILL_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAMA_SKILL` VARCHAR(50) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(50) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SKILL_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cvdb`.`skilldiri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`skilldiri` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`skilldiri` (
  `ID` INT(11) NOT NULL,
  `SKILL_ID` INT(11) NOT NULL,
  `KETERANGAN` VARCHAR(45) NULL DEFAULT NULL,
  `IS_ACTIVE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SKILL_ID`, `ID`),
  CONSTRAINT `cans_FK1`
    FOREIGN KEY (`SKILL_ID`)
    REFERENCES `cvdb`.`skill` (`SKILL_ID`),
  CONSTRAINT `cans_FK2`
    FOREIGN KEY (`ID`)
    REFERENCES `cvdb`.`datadiri` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `cans_FK3` ON `cvdb`.`skilldiri` (`ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
