-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 10:37:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cv` ;

-- -----------------------------------------------------
-- Schema cv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cv` DEFAULT CHARACTER SET utf8 ;
USE `cv` ;

-- -----------------------------------------------------
-- Table `cv`.`akun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`akun` ;

CREATE TABLE IF NOT EXISTS `cv`.`akun` (
  `akun_id` INT(11) NOT NULL AUTO_INCREMENT,
  `datadiri_id` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `pw` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`akun_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`datadiri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`datadiri` ;

CREATE TABLE IF NOT EXISTS `cv`.`datadiri` (
  `DATADIRI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAMA_LENGKAP` VARCHAR(50) NULL DEFAULT NULL,
  `UMUR` VARCHAR(45) NULL DEFAULT NULL,
  `TEMPAT_LAHIR` VARCHAR(25) NULL DEFAULT NULL,
  `TANGGAL_LAHIR` DATE NULL DEFAULT NULL,
  `GENDER` CHAR(1) NULL DEFAULT NULL,
  `AGAMA` VARCHAR(10) NULL DEFAULT NULL,
  `KEWARGANEGARAAN` VARCHAR(15) NULL DEFAULT NULL,
  `STATUS_PERKAWINAN` VARCHAR(8) NULL DEFAULT NULL,
  `TINGGI` VARCHAR(3) NULL DEFAULT NULL,
  `BERAT` VARCHAR(3) NULL DEFAULT NULL,
  `ALAMAT` VARCHAR(50) NULL DEFAULT NULL,
  `FOTO` VARCHAR(50) NULL DEFAULT NULL,
  `PROFIL_SINGKAT` VARCHAR(150) NULL DEFAULT NULL,
  `IS_ACTIVE` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`DATADIRI_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`organisasi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`organisasi` ;

CREATE TABLE IF NOT EXISTS `cv`.`organisasi` (
  `ORGANISASI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATADIRI_ID` INT(11) NULL DEFAULT NULL,
  `NAMA_ORGANISASI` VARCHAR(45) NULL DEFAULT NULL,
  `JABATAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ORGANISASI_ID`),
  INDEX `FK_ORGANISA_REFERENCE_DATADIRI` (`DATADIRI_ID` ASC),
  CONSTRAINT `FK_ORGANISA_REFERENCE_DATADIRI`
    FOREIGN KEY (`DATADIRI_ID`)
    REFERENCES `cv`.`datadiri` (`DATADIRI_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`pekerjaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`pekerjaan` ;

CREATE TABLE IF NOT EXISTS `cv`.`pekerjaan` (
  `PEKERJAAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATADIRI_ID` INT(11) NULL DEFAULT NULL,
  `NAMA_PERUSAHAAN` VARCHAR(45) NULL DEFAULT NULL,
  `JABATAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`PEKERJAAN_ID`),
  INDEX `FK_PEKERJAA_REFERENCE_DATADIRI` (`DATADIRI_ID` ASC),
  CONSTRAINT `FK_PEKERJAA_REFERENCE_DATADIRI`
    FOREIGN KEY (`DATADIRI_ID`)
    REFERENCES `cv`.`datadiri` (`DATADIRI_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`pendidikan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`pendidikan` ;

CREATE TABLE IF NOT EXISTS `cv`.`pendidikan` (
  `PENDIDIKAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATADIRI_ID` INT(11) NULL DEFAULT NULL,
  `NAMA_SEKOLAH` VARCHAR(50) NULL DEFAULT NULL,
  `JURUSAN` VARCHAR(30) NULL DEFAULT NULL,
  `KOTA` VARCHAR(30) NULL DEFAULT NULL,
  `TAHUN_MULAI` VARCHAR(4) NULL DEFAULT NULL,
  `TAHUN_SELESAI` VARCHAR(4) NULL DEFAULT NULL,
  `IPK` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`PENDIDIKAN_ID`),
  INDEX `FK_PENDIDIK_REFERENCE_DATADIRI` (`DATADIRI_ID` ASC),
  CONSTRAINT `FK_PENDIDIK_REFERENCE_DATADIRI`
    FOREIGN KEY (`DATADIRI_ID`)
    REFERENCES `cv`.`datadiri` (`DATADIRI_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`penghargaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`penghargaan` ;

CREATE TABLE IF NOT EXISTS `cv`.`penghargaan` (
  `PENGHARGAAN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATADIRI_ID` INT(11) NULL DEFAULT NULL,
  `PENGHARGAAN` VARCHAR(30) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(50) NULL DEFAULT NULL,
  `GAMBAR` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`PENGHARGAAN_ID`),
  INDEX `FK_PENGHARG_REFERENCE_DATADIRI` (`DATADIRI_ID` ASC),
  CONSTRAINT `FK_PENGHARG_REFERENCE_DATADIRI`
    FOREIGN KEY (`DATADIRI_ID`)
    REFERENCES `cv`.`datadiri` (`DATADIRI_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`skill` ;

CREATE TABLE IF NOT EXISTS `cv`.`skill` (
  `SKILL_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAMA_SKILL` VARCHAR(50) NULL DEFAULT NULL,
  `KETERANGAN` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`SKILL_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cv`.`skilldiri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv`.`skilldiri` ;

CREATE TABLE IF NOT EXISTS `cv`.`skilldiri` (
  `DATADIRI_ID` INT(11) NOT NULL,
  `SKILL_ID` INT(11) NOT NULL,
  `NAMA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`DATADIRI_ID`, `SKILL_ID`),
  INDEX `cans_FK2` (`SKILL_ID` ASC),
  CONSTRAINT `cans_FK1`
    FOREIGN KEY (`DATADIRI_ID`)
    REFERENCES `cv`.`skill` (`SKILL_ID`),
  CONSTRAINT `cans_FK2`
    FOREIGN KEY (`SKILL_ID`)
    REFERENCES `cv`.`datadiri` (`DATADIRI_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
